// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Generate(arg1:string):Promise<main.Response>;

export function PrintFile(arg1:string,arg2:number):Promise<main.Response>;
